global_costmap:
    global_frame: /map #Cannot be the same as robot base
    robot_base_frame: base_link_romi_pink
    update_frequency: 5.0 #Hz
    static_map: true #If false, rolling_window must be true

  # width: 8
  # height: 4
  # resolution: 0.092 #meters/cell
