global_costmap:
    global_frame: /map #Cannot be the same as robot base
    robot_base_frame: base_link_romi_white
    update_frequency: 5.0 #Hz
    static_map: true #If false, rolling_window must be true
    rolling_window: false #must be opposite of static_map?
                        #if rolling_window is true. Must define W,H,Resol

  # width: 2.438
  # height: 1.219
  # resolution: 0.092 #meters/cell
