local_costmap:
  global_frame: odom_romi_white
  robot_base_frame: base_link_romi_white
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: false
  width: 6.0
  height: 6.0
  resolution: 0.05
