TrajectoryPlannerROS:
  max_vel_x: 0.2286
  min_vel_x: -0.2286
  max_vel_theta: 0.2286
  min_in_place_vel_theta: 0
#Acceleration
  acc_lim_theta: 0.2286
  acc_lim_x: -0.2286
  acc_lim_y: 0.2286

  holonomic_robot: true
