local_costmap:
  global_frame: odom_romi_red
  robot_base_frame: base_link_romi_red
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true #Tutorial says to set True for no
                        #map server, but we have multiple robots?
                        #If static map is false. This must be true.
  width: 2.438
  height: 1.219
  resolution: 0.0254 #meters/cell
